const datosPatologias = [
    {
        identificador: 'colon_chagasico',
        nombre: 'Colon chagásico (Megacolon chagásico)',
        tipo: '3D',
        descripcionCorta: 'Dilatación masiva del colon por enf. de Chagas.',
        definicion: 'Alteración del intestino grueso caracterizada por una dilatación anormal y permanente del colon (megacolon) como consecuencia de la enfermedad de Chagas en su fase crónica.',
        causa: 'Infección por el parásito Trypanosoma cruzi, que daña el sistema nervioso entérico (plexos de Auerbach y Meissner) y provoca pérdida de la motilidad intestinal.',
        caracteristicas: 'Estreñimiento crónico severo; distensión abdominal; dolor abdominal; acumulación de heces (fecaloma); colon muy dilatado visible en estudios por imagen.',
        macro: 'Colon muy agrandado; pared intestinal adelgazada o a veces engrosada; gran acumulación de contenido fecal.',
        micro: 'Destrucción de neuronas del plexo mientérico; disminución o ausencia de ganglios nerviosos; inflamación crónica; fibrosis en la pared intestinal.',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Megacolon chagasico.glb',
    },
    {
        identificador: 'leiomioma_uterino',
        nombre: 'Leiomioma uterino',
        tipo: '3D',
        descripcionCorta: 'Tumor benigno de músculo liso en el útero.',
        definicion: 'Tumor benigno que se origina a partir del músculo liso del útero (miometrio), frecuente en mujeres en edad reproductiva.',
        causa: 'Proliferación anormal de células musculares lisas influida por hormonas, especialmente estrógenos; crecimiento durante la edad fértil y reducción tras la menopausia.',
        caracteristicas: 'Masa bien delimitada en el útero; puede ser única o múltiple; consistencia firme; puede causar sangrado menstrual abundante, dolor pélvico y presión sobre órganos vecinos.',
        macro: 'Masa uterina bien delimitada, firme; puede ser única o múltiple y variar en tamaño y localización (submucoso, intramural, subseroso).',
        micro: 'Fascículos de músculo liso organizados en remolinos; células uniformes sin atipia; núcleos alargados; ausencia de mitosis anormales.',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Leiomioma uterino.glb',
    },
    {
        identificador: 'mioma_uterino',
        nombre: 'Mioma uterino',
        tipo: '3D',
        descripcionCorta: 'Tumoración benigna uterina.',
        definicion: 'Tumor benigno del útero compuesto por tejido muscular y fibroso; término de uso clínico cotidiano equivalente al leiomioma.',
        causa: 'Crecimiento dependiente de hormonas (estrógenos y progesterona) que estimula la proliferación del tejido muscular del útero.',
        caracteristicas: 'Localización variable (submucoso, intramural, subseroso); puede deformar el útero; síntomas: sangrado irregular, dolor, y en algunos casos infertilidad.',
        macro: 'Nódulo o masa en la pared uterina que puede protruir hacia la cavidad (submucoso) o hacia la superficie (subseroso); tamaño variable y posible deformación uterina.',
        micro: 'Tejido de músculo liso con abundante colágeno organizado en haces; células sin signos de malignidad; baja actividad mitótica.',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Mioma uterino.glb',
    },
    {
        identificador: 'quiste_ovarico',
        nombre: 'Quiste ovárico',
        tipo: '3D',
        descripcionCorta: 'Saco lleno de líquido en el ovario.',
        definicion: 'Acumulación de líquido dentro del ovario que forma una cavidad quística.',
        causa: 'Alteraciones en la ovulación, por ejemplo un folículo que no se rompe o que no se reabsorbe.',
        caracteristicas: 'Puede ser asintomático; dolor pélvico leve; irregularidad menstrual; a veces hallazgo incidental en ecografía.',
        macro: 'Cavidad quística unilocular o multilocular dentro del ovario, rellena de líquido claro.',
        micro: 'Cavidad revestida por epitelio simple; contenido líquido; ausencia de invasión tumoral.',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Quiste ovarico.glb',
    },
    {
        identificador: 'cistoadenoma_seroso',
        nombre: 'Cistoadenoma seroso de ovario',
        tipo: '3D',
        descripcionCorta: 'Tumor benigno quístico del ovario.',
        definicion: 'Tumor benigno del ovario formado por quistes llenos de líquido seroso claro, originado del epitelio superficial ovárico.',
        causa: 'Proliferación epitelial anormal del epitelio superficial ovárico, posiblemente influida por factores hormonales.',
        caracteristicas: 'Masa quística generalmente unilateral; contenido líquido claro; suele ser asintomático y hallazgo incidental.',
        macro: 'Masa quística unilocular o multilocular en el ovario con contenido seroso claro; superficie lisa.',
        micro: 'Epitelio cilíndrico simple ciliado; pared delgada sin atipia; ausencia de invasión (característica benigna).',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Cistoadenoma seroso de ovario.glb',
    },
    {
        identificador: 'adenocarcinoma_colon',
        nombre: 'Adenocarcinoma de colon',
        tipo: '3D',
        descripcionCorta: 'Cáncer derivado del tejido glandular en colon.',
        definicion: 'Tumor maligno del colon originado en las glándulas epiteliales de la mucosa colónica.',
        causa: 'Mutaciones genéticas (p. ej. APC, KRAS, p53) asociadas a factores como dieta, inflamación crónica o predisposición genética.',
        caracteristicas: 'Sangrado rectal; pérdida de peso; cambio en hábitos intestinales; masa o estenosis en colon según la localización.',
        macro: 'Lesión polipoide o ulcerada que infiltra la pared colónica, posible estenosis o masa visible en estudios de imagen o colonoscopia.',
        micro: 'Glándulas irregulares infiltrantes; células atípicas con pleomorfismo; producción de moco en algunos casos.',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Adenocarcinoma de colon.glb',
    },
    {
        identificador: 'pielonefritis',
        nombre: 'Pielonefritis',
        tipo: '3D',
        descripcionCorta: 'Infección/inflamación renal.',
        definicion: 'Infección bacteriana del riñón que afecta la pelvis renal y el parénquima renal.',
        causa: 'Ascenso de bacterias desde las vías urinarias (por ejemplo Escherichia coli) hacia la pelvis renal y parénquima.',
        caracteristicas: 'Fiebre; dolor lumbar; disuria; signos sistémicos de infección; en casos crónicos puede haber daño renal persistente.',
        macro: 'Riñón inflamado con áreas de supuración o abscesos; posible aumento de tamaño y cambios en la superficie renal.',
        micro: 'Infiltrado neutrofílico intenso; destrucción tubular; formación de microabscesos en el parénquima renal.',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Pielonefritis.glb',
    },
    {
        identificador: 'colecistitis',
        nombre: 'Colecistitis',
        tipo: '3D',
        descripcionCorta: 'Inflamación de la vesícula biliar.',
        definicion: 'Inflamación de la vesícula biliar, generalmente secundaria a obstrucción del conducto cístico.',
        causa: 'Obstrucción del conducto cístico, habitualmente por cálculos biliares que provocan estasis e inflamación.',
        caracteristicas: 'Dolor en hipocondrio derecho; náuseas; fiebre; sensibilidad a la palpación en el cuadrante superior derecho.',
        macro: 'Vesícula biliar distendida o inflamada; engrosamiento de la pared; posible presencia de cálculos en la luz vesicular.',
        micro: 'Infiltrado inflamatorio en la pared; edema; engrosamiento de la mucosa y posible necrosis en casos severos.',
        imagen2d: '',
        modeloLocal: 'Imágenes/3D locales/Vesicula biliar.glb',
    },
    {
        identificador: 'fibrosis_pulmonar',
        nombre: 'Fibrosis pulmonar',
        tipo: '2D',
        descripcionCorta: 'Cicatrización del tejido pulmonar.',
        definicion: 'Enfermedad crónica en la que el tejido pulmonar se reemplaza progresivamente por tejido fibroso, volviéndose rígido y perdiendo capacidad de intercambio gaseoso.',
        causa: 'Idiopática o secundaria a factores como tabaquismo, contaminación, enfermedades autoinmunes o infecciones crónicas; daño repetido activa fibroblastos que producen colágeno.',
        caracteristicas: 'Disnea progresiva; tos seca persistente; disminución de la capacidad pulmonar; en fases avanzadas dedos en “palillo de tambor”.',
        macro: 'Pulmón duro y retraído con aspecto en “panal de abeja” en estadios avanzados.',
        micro: 'Engrosamiento de tabiques alveolares; fibrosis intersticial difusa; destrucción de la arquitectura pulmonar.',
        imagen2d: 'Imágenes/2D/Fribrosis Pulmonar.jpeg',
    },
    {
        identificador: 'hipertrofia_cardiaca',
        nombre: 'Hipertrofia cardíaca',
        tipo: '2D',
        descripcionCorta: 'Aumento del tamaño del músculo cardíaco.',
        definicion: 'Aumento del tamaño del corazón debido al crecimiento de las células musculares cardíacas (miocitos).',
        causa: 'Respuesta a sobrecarga de trabajo por hipertensión arterial, enfermedades valvulares o cardiopatías crónicas.',
        caracteristicas: 'Corazón agrandado; fatiga; disnea; riesgo de progresar a insuficiencia cardíaca.',
        macro: 'Engrosamiento de la pared ventricular, especialmente del ventrículo izquierdo; aumento del tamaño cardíaco.',
        micro: 'Miocitos aumentados de tamaño; núcleos grandes en “caja”; fibrosis intersticial variable.',
        imagen2d: 'Imágenes/2D/Hipertrofia Cardíaca.jpeg',
    },
    {
        identificador: 'tumor_cerebral',
        nombre: 'Tumor cerebral (Glioblastoma)',
        tipo: '2D',
        descripcionCorta: 'Tumor maligno agresivo del cerebro.',
        definicion: 'Tumor maligno primario del cerebro altamente agresivo originado en células gliales.',
        causa: 'Mutaciones genéticas en células gliales que alteran el control del crecimiento celular.',
        caracteristicas: 'Cefalea intensa; convulsiones; déficits neurológicos progresivos; evolución rápida y mal pronóstico.',
        macro: 'Masa cerebral irregular con áreas de necrosis y hemorragia; infiltración local del tejido cerebral.',
        micro: 'Células muy atípicas con pleomorfismo; necrosis con patrón en empalizada; alta actividad mitótica.',
        imagen2d: 'Imágenes/2D/Tumor Cerebral.jpeg',
    },
    {
        identificador: 'embolia_pulmonar',
        nombre: 'Embolia pulmonar',
        tipo: '2D',
        descripcionCorta: 'Bloqueo u obstrucción en arteria pulmonar.',
        definicion: 'Obstrucción de una arteria pulmonar por un émbolo, generalmente un coágulo procedente de venas profundas.',
        causa: 'Trombos venosos profundos que se desprenden y viajan al árbol pulmonar; factores de riesgo: inmovilidad, cirugías, anticonceptivos, trombofilia.',
        caracteristicas: 'Disnea súbita; dolor torácico; taquicardia; puede ser mortal si es extensa.',
        macro: 'Zona triangular hemorrágica o infarto pulmonar en el territorio irrigado por la arteria ocluida.',
        micro: 'Trombo o coágulo dentro del vaso pulmonar; necrosis y hemorragia del tejido pulmonar adyacente.',
        imagen2d: 'Imágenes/2D/Embolia Pulmonar .jpeg',
    },
    {
        identificador: 'aterosclerosis',
        nombre: 'Aterosclerosis',
        tipo: '2D',
        descripcionCorta: 'Acumulación de grasas y colesterol en arterias.',
        definicion: 'Enfermedad de las arterias caracterizada por la formación de placas de lípidos y tejido fibroso en la pared arterial.',
        causa: 'Daño endotelial asociado a colesterol alto, tabaquismo, diabetes e hipertensión que favorece la acumulación lipídica y la inflamación crónica.',
        caracteristicas: 'Disminución del flujo sanguíneo; riesgo aumentado de infarto de miocardio o accidente cerebrovascular.',
        macro: 'Arterias endurecidas y estrechas con placas visibles en la luz arterial.',
        micro: 'Placas lipídicas con macrófagos cargados de lípidos (células espumosas) y fibrosis en la íntima arterial.',
        imagen2d: 'Imágenes/2D/Ateroesclerosis.jpeg',
    },
    {
        identificador: 'hemorragia_cerebral',
        nombre: 'Hemorragia cerebral',
        tipo: '2D',
        descripcionCorta: 'Sangrado interno en el tejido cerebral.',
        definicion: 'Extravasación de sangre dentro del tejido cerebral por ruptura vascular.',
        causa: 'Hipertensión arterial, ruptura de vasos, traumatismos u otras lesiones vasculares.',
        caracteristicas: 'Inicio súbito; pérdida de conciencia; déficits neurológicos focales; cefalea intensa.',
        macro: 'Acumulación de sangre en el parénquima cerebral con efecto de masa y desplazamiento de estructuras.',
        micro: 'Sangre fuera de los vasos; daño neuronal y edema circundante.',
        imagen2d: 'Imágenes/2D/Hemorragia Cerebral.jpeg',
    },
    {
        identificador: 'neumotorax',
        nombre: 'Neumotórax',
        tipo: '2D',
        descripcionCorta: 'Presencia de aire en la cavidad pleural.',
        definicion: 'Aire en la cavidad pleural que provoca colapso parcial o total del pulmón afectado.',
        causa: 'Traumatismos, ruptura espontánea de alveolos o enfermedades pulmonares subyacentes.',
        caracteristicas: 'Dolor torácico súbito; disnea; disminución de los ruidos respiratorios en el lado afectado.',
        macro: 'Pulmón colapsado con aire en la cavidad pleural; posible desplazamiento mediastínico si es a tensión.',
        micro: 'Colapso alveolar y pérdida de expansión pulmonar en la zona afectada.',
        imagen2d: 'Imágenes/2D/Neumotorax.jpeg',
    },
    {
        identificador: 'insuficiencia_cardiaca',
        nombre: 'Insuficiencia cardíaca',
        tipo: '2D',
        descripcionCorta: 'Bombeo deficiente del corazón.',
        definicion: 'Incapacidad del corazón para bombear sangre de forma adecuada para satisfacer las necesidades del organismo.',
        causa: 'Infarto de miocardio, hipertensión, enfermedades valvulares u otras cardiopatías que dañan la función contráctil.',
        caracteristicas: 'Disnea; edema periférico (piernas); fatiga; congestión pulmonar y signos de retención hídrica.',
        macro: 'Corazón dilatado con posible hipertrofia y cambios estructurales según la etiología.',
        micro: 'Fibrosis intersticial; degeneración de miocitos; cambios celulares asociados a sobrecarga crónica.',
        imagen2d: 'Imágenes/2D/Insuficiencia Cardiaca.jpeg',
    }, 
    {
        identificador: 'cirrosis_hepatica',
        nombre: 'Cirrosis hepática',
        tipo: '2D',
        descripcionCorta: 'Daño crónico y cicatrización del hígado.',
        definicion: 'Enfermedad crónica del hígado caracterizada por fibrosis difusa y formación de nódulos regenerativos que alteran la arquitectura hepática.',
        causa: 'Consumo crónico de alcohol, hepatitis viral crónica o enfermedades metabólicas que provocan daño hepático progresivo.',
        caracteristicas: 'Ictericia; ascitis; fatiga; signos de insuficiencia hepática y complicaciones portal-hipertensivas.',
        macro: 'Hígado nodular y duro con superficie irregular y reducción del volumen funcional.',
        micro: 'Fibrosis difusa con nódulos regenerativos y alteración de la arquitectura hepática normal.',
        imagen2d: 'Imágenes/2D/Cirrosis Hepática.jpeg',
    },
    {
        identificador: 'osteosarcoma',
        nombre: 'Osteosarcoma',
        tipo: '2D',
        descripcionCorta: 'Cáncer primario de los huesos.',
        definicion: 'Tumor maligno del hueso caracterizado por la producción de tejido óseo anormal (osteoide).',
        causa: 'Mutaciones genéticas (p. ej. p53, RB) que alteran el control del crecimiento celular; más frecuente en jóvenes.',
        caracteristicas: 'Dolor óseo progresivo; masa palpable; fracturas patológicas; crecimiento rápido localmente agresivo.',
        macro: 'Lesión ósea destructiva que puede producir masa blanda adyacente y destrucción cortical.',
        micro: 'Células malignas pleomórficas que producen osteoide; alta actividad mitótica.',
        imagen2d: 'Imágenes/2D/Osteosarcoma.jpeg',
    }
];

window.datosPatologias = datosPatologias;
